import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'

import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/components/modal-provider'
import { CrispProvider } from '@/components/crisp-provider'


const inter = Roboto({ subsets: ['latin'], weight: '500' })

export const metadata: Metadata = {
  title: 'Egihub',
  description: 'Generated by Egihub',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <CrispProvider />
        <body className={inter.className}>
          <ModalProvider />
          {children}</body>
      </html>
    </ClerkProvider>
  )
}
